config/routes.rb
Rails.application.routes.draw do
  root 'public#home'
  get 'home2', to: 'public#home2'
  get 'about-ucubed', to: 'public#about_ucubed'
  get 'articles', to: 'public#articles'
  get 'free_resources', to: 'public#free_resources'
  # get 'test4', to: 'public#test4'
  get 'learn', to: "public#learn"
  get 'join', to: "public#join"
  get 'partner', to: "public#partner"
  get 'explore', to: "public#explore"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def home
  end

  def learn
  end

  def join
  end

  def partner
  end

  def about_ucubed
  end

  def articles
  end

  def free_resources
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def explore_page?
    current_page?(about_ucubed_path) or current_page?(articles_path) or current_page?(free_resources_path)
  end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer" data-bg-color="#D9E0DD">
        <div class="container">
            <div class="main_footer">
                <div class="row">
                    <div class="col-xl-5 col-md-6">
                        <div class="site_info logo_area wow fadeInLeft" data-wow-delay="0.3s">
                            <img src="assets/img/logo/logo.png" alt="" class="footer_logo">
                            <p>Main factor that sets us apart competition allows deliver a specialist business
                                consultancy service applies its ranging experience</p>
                            <div class="social_icons">
                                <a href="https://facebook.com"><i class="fa-brands fa-facebook-f"></i></a>
                                <a href="https://twitter.com/"><i class="fa-brands fa-twitter"></i></a>
                                <a href="https://bd.linkedin.com/"><i class="fa-brands fa-linkedin-in"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 mid">
                        <div class="site_info wow fadeInLeft" data-wow-delay="0.5s">
                            <h5>Contact info</h5>
                            <ul class="loc_list list-unstyled">
                                <li>Neal St, London WC2H 9PR</li>
                                <li>United Kingdom</li>
                            </ul>
                            <ul class="contact_list list-unstyled">
                                <li class="mail"><a href="mailto:info.calmor@support.com">info.calmor@support.com</a>
                                </li>
                                <li><a href="tel:44793123456">+44 1793 123 456</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 last">
                        <div class="site_info wow fadeInLeft" data-wow-delay="0.7s">
                            <h5>Subscribe newsletter</h5>
                            <form action="#" class="subscribe_form">
                                <input type="email" class="form-control" placeholder="Enter your email address">
                                <input type="submit" class="bg_btn_color" value="Subscribe">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer_bottom wow fadeInLeft" data-wow-delay="0.9s">
                <div class="footer_bottom_list">
                    <div class="row">
                        <div class="col-xl-6">
                            <ul class="footer_nav list-unstyled">
                                <li><a href="portfolio-2-column.html">Portfolio</a></li>
                                <li><a href="team.html">our team</a></li>
                                <li><a href="pricing.html">pricing plan</a></li>
                                <li><a href="service.html">Services</a></li>
                                <li><a href="contact.html">contact us</a></li>
                            </ul>
                        </div>
                        <div class="col-xl-6">
                            <ul class="footer_nav right list-unstyled">
                                <li><a href="contact.html">Terms & conditions</a></li>
                                <li><a href="contact.html">privacy policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="footer_copyright">
                    <p>© 2022 PicmaticWeb, All Rights Reserved </p>
                </div>
            </div>
        </div>
        <div class="shape_img">
            <img src="assets/img/footer/1.png" alt="" class="one wow fadeInLeft" data-wow-delay="1.3s">
            <img src="assets/img/footer/2.png" alt="" class="two wow fadeInLeft" data-wow-delay="1.1s">
            <img src="assets/img/footer/3.png" alt="" class="three wow fadeInLeft" data-wow-delay="0.1s">
        </div>
    </footer>

app/views/layouts/_header-assets.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" integrity="sha512-+EoPw+Fiwh6eSeRK7zwIKG2MA8i3rV/DGa3tdttQGgWyatG/SkncT53KHQaS5Jh9MNOT3dmFL0FjTY08And/Cw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.compat.min.css" integrity="sha512-b42SanD3pNHoihKwgABd18JUZ2g9j423/frxIP5/gtYgfBz/0nDHGdY/3hi+3JwhSckM3JLklQ/T6tJmV7mZEw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://kit.fontawesome.com/2fbcf4bc83.js" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
<script type="text/javascript">
  WebFont.load({
    google: {
      families: ["Jost:regular,500,600,700,800", "Poppins:regular,500,600,700,800"]
    }
  });
</script><!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif]-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/noframework.waypoints.min.js" integrity="sha512-fHXRw0CXruAoINU11+hgqYvY/PcsOWzmj0QmcSOtjlJcqITbPyypc8cYpidjPurWpCnlB8VKfRwx6PIpASCUkQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js" integrity="sha512-IsNh5E3eYy3tr/JiX2Yx4vsCujtkhwl7SLqgnwLNgf04Hrt9BT9SXlLlZlWx+OK4ndzAoALhsMNcCmkggjZB1w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" integrity="sha512-Eak/29OTpb36LLo2r47IpVzPBLXnAMPAVypbSZiZ4Qkf8p/7S/XRG5xp7OKWPPYfJT6metI+IORkR5G8F900+g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js" integrity="sha512-d8F1J2kyiRowBB/8/pAWsqUl0wSEOkG5KATkVV4slfblq9VRQ6MyDZVxWl2tWd+mPhuCbpTB4M7uU/x9FlgQ9Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/3.1.0/parallax.min.js" integrity="sha512-/6TZODGjYL7M8qb7P6SflJB/nTGE79ed1RfJk3dfm/Ib6JwCT4+tOfrrseEHhxkIhwG8jCl+io6eaiWLS/UX1w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js" integrity="sha512-57oZ/vW8ANMjR/KQ6Be9v/+/h6bq9/l3f0Oc7vn6qMqyhvPd1cvKBRWWpzu0QoneImqr2SkmO4MSqU+RpHom3Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdn.jsdelivr.net/gh/fluffy-factory/magnet-mouse@latest/lib/magnet-mouse.min.js"></script>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

app/views/layouts/_js.html.erb
<script type="text/javascript">
  /** @format */

  (function ($) {
  	'use strict';

          //*============ background image js ==============*/
      $('[data-bg-img]').each(function () {
          var bg = $(this).data('bg-img');
          $(this).css({
              background: 'no-repeat center 0/cover url(' + bg + ')',
          });
      });

      // background color js
      $('[data-bg-color]').each(function () {
          var bgcolor = $(this).data('bg-color');
          $(this).css({
              'background-color': bgcolor,
          });
      });

      // Nav Bar Fix
      function navbarFixed() {
          if ($('.header_aria').length) {
              $(window).scroll(function () {
                  var scroll = $(window).scrollTop();
                  if (scroll) {
                      $('.header_aria').addClass('navbar_fixed');
                  } else {
                      $('.header_aria').removeClass('navbar_fixed');
                  }
              });
          }
      }
      navbarFixed();

      function menu_dropdown() {
          if ($(window).width() < 992) {
              $('.navbar-nav > li .mobile_dropdown_icon').on('click', function (event) {
                  event.preventDefault();
                  $(this).parent().find('.dropdown-menu').first().slideToggle(700);
                  $(this).parent().siblings().find('.dropdown-menu').slideUp(700);
              });
          }
      }
      menu_dropdown();

      //   Magnific Popup
      $(document).ready(function () {
          $('.popup_btn').magnificPopup({
              type: 'iframe',
          });
      });


      //	  Slick js

      $('.min_team_area').slick({
          autoplay: true,
          infinite: true,
          slidesToShow: 3,
          slidesToScroll: 1,
          dots: true,
          arrows: false,
          speed: 300,
          responsive: [
              {
                  breakpoint: 1200,
                  settings: {
                      slidesToShow: 2,
                  }
              },
              {
                  breakpoint: 768,
                  settings: {
                      slidesToShow: 1,
                  }
              }
          ]
      });
      $('.min_testimonial_area').slick({
          autoplay: true,
          infinite: true,
          slidesToShow: 1,
          slidesToScroll: 1,
          dots: false,
          arrows: true,
          speed: 300,
          prevArrow:
                  '<button type="button" class="slick-prev"><i class="fa-solid fa-angle-left"></i></button>',
              nextArrow:
                  '<button type="button" class="slick-next"><i class="fa-solid fa-angle-right"></i></button>',
      });
      $('.testimonial_style_two_area').slick({
          autoplay: true,
          infinite: true,
          slidesToShow: 2,
          slidesToScroll: 1,
          dots: false,
          arrows: true,
          speed: 300,
          prevArrow:
                  '<button type="button" class="slick-prev"><i class="fa-solid fa-angle-left"></i></button>',
              nextArrow:
                  '<button type="button" class="slick-next"><i class="fa-solid fa-angle-right"></i></button>',
          responsive: [
              {
                  breakpoint: 768,
                  settings: {
                      slidesToShow: 1,
                      }
              }
          ]
      });
      $('.min_blog_area').slick({
          autoplay: true,
          infinite: true,
          slidesToShow: 2,
          slidesToScroll: 1,
          dots: true,
          arrows: false,
          speed: 300,
          responsive: [
              {
                  breakpoint: 992,
                  settings: {
                      slidesToShow: 1,
                  }
              }
          ]
      });
      $('.min_blog_area_col_3').slick({
          autoplay: true,
          infinite: true,
          slidesToShow: 3,
          slidesToScroll: 1,
          dots: true,
          arrows: false,
          speed: 300,
          responsive: [
              {
                  breakpoint: 1400,
                  settings: {
                      slidesToShow: 2,
                      }
              },
              {
                  breakpoint: 992,
                  settings: {
                      slidesToShow: 1,
                      }
              }
          ]
      });
      $('.min_shop_area').slick({
          autoplay: true,
          infinite: true,
          slidesToShow: 3,
          slidesToScroll: 1,
          dots: true,
          arrows: false,
          speed: 300,
          responsive: [
              {
                  breakpoint: 1200,
                  settings: {
                      slidesToShow: 2,
                  }
              },
              {
                  breakpoint: 768,
                  settings: {
                      slidesToShow: 1,
                  }
              }
          ]
      });
      $('.min_project_slider_area').slick({
          autoplay: true,
          infinite: true,
          slidesToShow: 3,
          slidesToScroll: 1,
          dots: false,
          arrows: false,
          speed: 300,
          responsive: [
              {
                  breakpoint: 992,
                  settings: {
                      slidesToShow: 2,
                  }
              },
              {
                  breakpoint: 768,
                  settings: {
                      slidesToShow: 1,
                  }
              }
          ]
      });
      $('.min_project_slider_two_area').slick({
          slidesToShow: 2,
          slidesToScroll: 1,
          autoplay: true,
          infinite: true,
          centerMode: true,
          centerPadding: '495px',
          arrows: false,
          dots: false,
          responsive: [
              {
                  breakpoint: 1200,
                  settings: {
                      slidesToShow: 1,
                      centerPadding: '100px',
                  }
              },
              {
                  breakpoint: 500,
                  settings: {
                      centerPadding: '0',
                  }
              }
          ]
      });
      $('.line_item').slick({
          speed: 8000,
          autoplay: true,
          autoplaySpeed: 1000,
          centerMode: true,
          cssEase: 'linear',
          slidesToShow: 1,
          slidesToScroll: 1,
          variableWidth: true,
          infinite: true,
          initialSlide: 1,
          arrows: false,
          buttons: false,
      });

      // Counter js

      function counterUp() {
          if ($('.counter').length) {
              $('.counter').counterUp({
                  delay: 1,
                  time: 500,
              });
          }
      }

      counterUp();

      // wow js
      function bodyScrollAnimation() {
          var scrollAnimate = $('body').data('scroll-animation');
          if (scrollAnimate === true) {
              new WOW({}).init();
          }
      }
      bodyScrollAnimation();

      //    Progress-bar....//
      $('.single_items').each(function () {
          $(this).waypoint(
              function () {
                  var progressBar = $('.progress-bar');
                  progressBar.each(function (indx) {
                      $(this).css('width', $(this).attr('aria-valuenow') + '%');
                  });
              },
              {
                  triggerOnce: true,
                  offset: 'bottom-in-view',
              }
          );
      });


      // Magnitic Hover
      let mm = new MagnetMouse({
          magnet: {
          element: '.popup_btn'
          }
      });

      mm.init();

      // Jqueray Ui
      $( function() {
          $( "#slider-range" ).slider({
          range: true,
          min: 0,
          max: 500,
          values: [ 75, 300 ],
          slide: function( event, ui ) {
              $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
          }
          });
          $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
          " - $" + $( "#slider-range" ).slider( "values", 1 ) );
      } );

      //Product Details Slider
      $('.slider_one').slick({
          infinite: false,
          autoplay: false,
          slidesToShow: 1,
          slidesToScroll: 1,
          arrows: false,
          fade: true,
          asNavFor: '.slider_nav',
      });

      $('.slider_nav').slick({
          infinite: true,
          autoplay: true,
          autoplaySpeed: 2000,
          slidesToShow: 3,
          slidesToScroll: 1,
          asNavFor: '.slider_one',
          dots: true,
          centerMode: true,
          focusOnSelect: true,
      });

  })(jQuery);

</script>

app/views/layouts/_navbar-bak.html.erb
<!-- <div class="container px-5 mt-2 bg-transparent rounded-4">
  <nav class="navbar py-3 navbar-expand-lg mb-5">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span style="font-family:Comfortaa;font-size:80px;font-weight:600;" class="text-white">Ucubed</span>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse flex-grow-1 text-right" id="navbarNavDropdown">
        <ul class="navbar-nav">

          <li class="nav-item">
            <a class="nav-link" href="/learn">Learn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/join">Join</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/partner">Partner</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Discover
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/explore">Explore</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>
      </div>
    </nav>
  </div> -->

  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-transparent px-0 py-3">
    <div class="container-xl">
      <!-- Logo -->
      <a class="navbar-brand" href="/">
        <!-- <img src="https://preview.webpixels.io/web/img/logos/clever-primary.svg" class="h-8" alt="..."> -->
        Ucubed
      </a>
      <!-- Navbar toggle -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <!-- Nav -->
        <div class="navbar-nav mx-lg-auto">
          <a class="nav-item nav-link active px-4" href="#" aria-current="page">Home</a>
          <a class="nav-item nav-link px-4" href="#">Learn</a>
          <a class="nav-item nav-link px-4" href="#">Join</a>
          <a class="nav-item nav-link px-4" href="#">Partner</a>
        </div>
        <!-- Right navigation -->
        <div class="navbar-nav ms-lg-4">
          <a class="nav-item nav-link" href="#">Sign in</a>
        </div>
        <!-- Action -->
        <div class="d-flex align-items-lg-center mt-3 mt-lg-0">
          <!-- <a href="#" class="btn btn-sm btn-primary w-full w-lg-auto">
            Register
          </a> -->
        </div>
      </div>
    </div>
  </nav>

app/views/layouts/_navbar-bak2.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light px-0 py-3" style="background-color:#F9F4E6;">
  <div class="container-xl">
    <!-- Logo -->
    <a class="navbar-brand gradient-text" href="/">
      <!-- <img src="https://preview.webpixels.io/web/img/logos/clever-primary.svg" class="h-8" alt="..."> -->
      <%= image_tag 'OrangeU.png', class: 'img-fluid', style: 'max-height:60px;' %>
    </a>
    <!-- Navbar toggle -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <!-- Nav -->
      <div class="navbar-nav mx-lg-auto"></div>
      <!-- Right navigation -->
      <div class="navbar-nav ms-lg-4">
        <a class="nav-item nav-link px-4 <%= current_page?(root_path) ? 'active' : '' %>" href="/" aria-current="page">
          <i class="fa-solid fa-house-chimney-window fa-fw"></i>
          &nbsp; Home</a>
        <a class="nav-item nav-link px-4  <%= current_page?(learn_path) ? 'active' : '' %>" href="/learn">
          <i class="fa-solid fa-lines-leaning"></i>
          &nbsp; Learn</a>
        <a class="nav-item nav-link px-4  <%= current_page?(join_path) ? 'active' : '' %>" href="/join">
          <i class="fa-solid fa-globe"></i>
          &nbsp; Community</a>
        <a class="nav-item nav-link px-4  <%= current_page?(partner_path) ? 'active' : '' %>" href="/partner">
          <i class="fa-solid fa-handshake"></i>
          &nbsp; Partner</a>
        <!-- <a class="nav-item nav-link px-4" href="/explore"><i class="fa-solid fa-compass"></i> &nbsp; Explore</a> -->
        <li class="nav-item dropdown">
          <a class="nav-link px-4 dropdown-toggle <%= explore_page? ? 'active' : '' %>" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-compass"></i>
            &nbsp; Explore
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="/about-ucubed">About Ucubed</a>
            </li>
            <li>
              <a class="dropdown-item" href="/articles">Articles</a>
            </li>
            <li>
              <a class="dropdown-item" href="/free_resources">Free resources</a>
            </li>
          </ul>
        </li>
        <!-- <a class="nav-item nav-link px-4" href="#">Sign in</a> -->
      </div>
      <!-- Action -->
      <div class="d-flex align-items-lg-center mt-3 mt-lg-0">
        <!-- <a href="#" class="btn btn-sm btn-primary w-full w-lg-auto"> Register </a> -->
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<header class="header_aria">
    <nav class="navbar navbar-expand-lg fixed-top bg-transfaren">
        <div class="container">
            <a class="navbar-brand" href="/">
                <%= image_tag "u3-2.png", class: "image-fluid", style: "width: 5rem;" %>
                <!-- U<sup>3</sup> -->
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"><i class="fa-solid fa-bars"></i></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                      <a class="nav-link" href="/"><i class="fa-solid fa-house-chimney"></i> </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="/learn">Learn</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="/join">Join</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="/partner">Partner</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Discover
                      </a>
                      <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="/explore">Explore</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                      </ul>
                    </li>
                </ul>
                <div class="nav_buttons">
                    <a href="/about" class="cart">About</a>
                    <a href="/free-web3-workshop" class="contact_btn">Free IRL Workshops</a>
                </div>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application-bak.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cubed</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="pt-5">
  <%= render partial: "layouts/navbar" %>
  <main class="container">
    <%= yield %>
  </main>
  <script src="https://han109k.github.io/light-switch-bootstrap/switch.js"></script>
  <script type="text/javascript">
    (function () {
      if (!lightSwitch) {
        return;
      }
    })();
  </script>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>UCUBED - Learn web3 digital skills and level up your life.</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/header-assets' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <%= render 'layouts/js' %>
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
  </body>
</html>